export interface IPersonalien {
  baPersonID: number;
  statusPersonCode: number;
  titel: string;
  name: string;
  fruehererName: string;
  vorname: string;
  vorname2: string;
  geburtsdatum: Date;
  sterbedatum: Date;
  aHVNummer: string;
  versichertennummer: string;
  haushaltVersicherungsNummer: string;
  nNummer: string;
  bFFNummer: string;
  zARNummer: string;
  zIPNr: number;
  kantonaleReferenznummer: string;
  geschlechtCode: number;
  zivilstandCode: number;
  zivilstandDatum: Date;
  heimatgemeindeCode: number;
  heimatgemeindeCodes: string;
  nationalitaetCode: number;
  religionCode: number;
  auslaenderStatusCode: number;
  auslaenderStatusGueltigBis: Date;
  telefon_P: string;
  telefon_G: string;
  mobilTel1: string;
  mobilTel2: string;
  eMail: string;
  sprachCode: number;
  unterstuetzt: boolean;
  fiktiv: boolean;
  bemerkung: string;
  einwohnerregisterAktiv: boolean;
  einwohnerregisterID: string;
  deutschVerstehenCode: number;
  wichtigerHinweisCode: number;
  zuzugKtPLZ: string;
  zuzugKtOrtCode: number;
  zuzugKtOrt: string;
  zuzugKtKanton: string;
  zuzugKtLandCode: number;
  zuzugKtDatum: Date;
  zuzugKtSeitGeburt: boolean;
  zuzugGdePLZ: string;
  zuzugGdeOrtCode: number;
  zuzugGdeOrt: string;
  zuzugGdeKanton: string;
  zuzugGdeLandCode: number;
  zuzugGdeDatum: Date;
  zuzugGdeSeitGeburt: boolean;
  zntWohnsitzPLZ: string;
  zntWohnsitzOrt: string;
  zntWohnsitzKanton: string;
  zntWohnsitzLandCode: number;
  wegzugPLZ: string;
  wegzugOrtCode: number;
  wegzugOrt: string;
  wegzugKanton: string;
  wegzugLandCode: number;
  wegzugDatum: Date;
  wohnsitzWieBaPersonID: number;
  aufenthaltWieBaInstitutionID: number;
  erwerbssituationCode: number;
  grundTeilzeitarbeit1Code: number;
  grundTeilzeitarbeit2Code: number;
  baGrundNichtErwerbstaetigCode: number;
  erwerbsBrancheCode: number;
  erlernterBerufCode: number;
  berufCode: number;
  hoechsteAusbildungCode: number;
  abgebrocheneAusbildungCode: number;
  arbeitSpezFaehigkeiten: string;
  kbKostenstelleID: number;
  inCHSeit: Date;
  inCHSeitGeburt: boolean;
  pUAnzahlVerlustscheine: number;
  pUKrankenkasse: string;
  praemienuebernahmeVon: Date;
  praemienuebernahmeBis: Date;
  personOhneLeistung: boolean;
  hCMCFluechtling: boolean;
  stellensuchendCode: number;
  resoNr: number;
  nEAnmeldung: Date;
  heimatgemeindeBaGemeindeID: number;
  aktiveKopfQuote: boolean;
  aLK: boolean;
  andereSVLeistungen: string;
  anrede: string;
  ausbildungCode: number;
  behinderungsart2Code: number;
  bemerkungenAdresse: string;
  bemerkungenSV: string;
  beruflicheMassnahmeIV: boolean;
  briefanrede: string;
  bSVBehinderungsartCode: number;
  bVGRente: boolean;
  cAusweisDatum: Date;
  klientenkontoNr: number;
  debitorNr: number;
  debitorUpdate: Date;
  eigenerMietvertrag: boolean;
  einrichtpauschale: number;
  einrichtungspauschaleCode: number;
  ergaenzungsLeistungen: boolean;
  assistenzbeitrag: boolean;
  datumAssistenzbeitrag: Date;
  ivVerfuegteAssistenzberatung: number;
  datumIvVerfuegung: Date;
  erteilungVA: Date;
  istFamiliennachzug: boolean;
  fax: string;
  hauptBehinderungsartCode: number;
  hELBKeinAntrag: boolean;
  hELBAb: Date;
  hELBAnmeldung: Date;
  hELBEntscheid: Date;
  hELBEntscheidCode: number;
  hilfslosenEntschaedigungCode: number;
  imKantonSeit: Date;
  imKantonSeitGeburt: boolean;
  inGemeindeSeit: Date;
  intensivPflegeZuschlagCode: number;
  iVBerechtigungAnfangsStatusCode: number;
  iVBerechtigungErsterEntscheidAb: Date;
  iVBerechtigungErsterEntscheidCode: number;
  iVBerechtigungZweiterEntscheidAb: Date;
  iVBerechtigungZweiterEntscheidCode: number;
  iVGrad: number;
  iVHilfsmittel: boolean;
  iVTaggeld: boolean;
  keinSerienbrief: boolean;
  konfessionCode: number;
  kontoFuehrung: boolean;
  baPersonID_Dossiertraeger: number;
  kopfquote_BaInstitutionID: number;
  kopfquoteAbDatum: Date;
  kopfquoteBisDatum: Date;
  korrespondenzSpracheCode: number;
  kTG: boolean;
  laufendeVollmachtErlaubnis: boolean;
  manuelleAnrede: boolean;
  medizinischeMassnahmeIV: boolean;
  mehrfachbehinderung: boolean;
  mietdepotPI: boolean;
  migrationKA: number;
  mobilTel: string;
  navigatorZusatz: string;
  passiveKopfQuote: boolean;
  pauschaleAktualDatum: Date;
  personSichtbarSDFlag: boolean;
  projNr: number;
  rentenstufeCode: number;
  sichtbarSDFlag: boolean;
  sozialhilfe: boolean;
  sprachpauschale: number;
  testperson: boolean;
  untWohnsitzOrtCode: number;
  uVGRente: boolean;
  uVGTaggeld: boolean;
  verstaendigungSprachCode: number;
  visdat36Area: string;
  visdat36ID: string;
  vormundMassnahmenCode: number;
  vormundPI: boolean;
  wichtigerHinweis: string;
  wittwenWittwerWaisenrente: boolean;
  wohnstatusCode: number;
  zeigeDetails: boolean;
  zeigeTelGeschaeft: boolean;
  zeigeTelMobil: boolean;
  zeigeTelPrivat: boolean;
  zEMISNummer: string;
  istBerechnungsperson: boolean;
  datumAsylgesuch: Date;
  datumEinbezugFaz: Date;
  verID: number;
  creator: string;
  created: Date;
  modifier: string;
  modified: Date;
  verID_DELETED: number;
  heimatort: string;
  konfessionName: string;
  auslaenderStatusName: string;
  sprachName: string;
  zivilstandName: string;
  nationalitaetName: string;
  untWohnsitzLandName: string;
  zuzugKtLandName: string;
  zuzugGdeLandName: string;
  wegzugLandName: string;
  geschlechtName: string;
}

export class Personalien implements IPersonalien {
  public baPersonID: number;
  public statusPersonCode: number;
  public titel: string;
  public name: string;
  public fruehererName: string;
  public vorname: string;
  public vorname2: string;
  public geburtsdatum: Date;
  public sterbedatum: Date;
  public aHVNummer: string;
  public versichertennummer: string;
  public haushaltVersicherungsNummer: string;
  public nNummer: string;
  public bFFNummer: string;
  public zARNummer: string;
  public zIPNr: number;
  public kantonaleReferenznummer: string;
  public geschlechtCode: number;
  public zivilstandCode: number;
  public zivilstandDatum: Date;
  public heimatgemeindeCode: number;
  public heimatgemeindeCodes: string;
  public nationalitaetCode: number;
  public religionCode: number;
  public auslaenderStatusCode: number;
  public auslaenderStatusGueltigBis: Date;
  public telefon_P: string;
  public telefon_G: string;
  public mobilTel1: string;
  public mobilTel2: string;
  public eMail: string;
  public sprachCode: number;
  public unterstuetzt: boolean;
  public fiktiv: boolean;
  public bemerkung: string;
  public einwohnerregisterAktiv: boolean;
  public einwohnerregisterID: string;
  public deutschVerstehenCode: number;
  public wichtigerHinweisCode: number;
  public zuzugKtPLZ: string;
  public zuzugKtOrtCode: number;
  public zuzugKtOrt: string;
  public zuzugKtKanton: string;
  public zuzugKtLandCode: number;
  public zuzugKtDatum: Date;
  public zuzugKtSeitGeburt: boolean;
  public zuzugGdePLZ: string;
  public zuzugGdeOrtCode: number;
  public zuzugGdeOrt: string;
  public zuzugGdeKanton: string;
  public zuzugGdeLandCode: number;
  public zuzugGdeDatum: Date;
  public zuzugGdeSeitGeburt: boolean;
  public zntWohnsitzPLZ: string;
  public zntWohnsitzOrt: string;
  public zntWohnsitzKanton: string;
  public zntWohnsitzLandCode: number;
  public wegzugPLZ: string;
  public wegzugOrtCode: number;
  public wegzugOrt: string;
  public wegzugKanton: string;
  public wegzugLandCode: number;
  public wegzugDatum: Date;
  public wohnsitzWieBaPersonID: number;
  public aufenthaltWieBaInstitutionID: number;
  public erwerbssituationCode: number;
  public grundTeilzeitarbeit1Code: number;
  public grundTeilzeitarbeit2Code: number;
  public baGrundNichtErwerbstaetigCode: number;
  public erwerbsBrancheCode: number;
  public erlernterBerufCode: number;
  public berufCode: number;
  public hoechsteAusbildungCode: number;
  public abgebrocheneAusbildungCode: number;
  public arbeitSpezFaehigkeiten: string;
  public kbKostenstelleID: number;
  public inCHSeit: Date;
  public inCHSeitGeburt: boolean;
  public pUAnzahlVerlustscheine: number;
  public pUKrankenkasse: string;
  public praemienuebernahmeVon: Date;
  public praemienuebernahmeBis: Date;
  public personOhneLeistung: boolean;
  public hCMCFluechtling: boolean;
  public stellensuchendCode: number;
  public resoNr: number;
  public nEAnmeldung: Date;
  public heimatgemeindeBaGemeindeID: number;
  public aktiveKopfQuote: boolean;
  public aLK: boolean;
  public andereSVLeistungen: string;
  public anrede: string;
  public ausbildungCode: number;
  public behinderungsart2Code: number;
  public bemerkungenAdresse: string;
  public bemerkungenSV: string;
  public beruflicheMassnahmeIV: boolean;
  public briefanrede: string;
  public bSVBehinderungsartCode: number;
  public bVGRente: boolean;
  public cAusweisDatum: Date;
  public klientenkontoNr: number;
  public debitorNr: number;
  public debitorUpdate: Date;
  public eigenerMietvertrag: boolean;
  public einrichtpauschale: number;
  public einrichtungspauschaleCode: number;
  public ergaenzungsLeistungen: boolean;
  public assistenzbeitrag: boolean;
  public datumAssistenzbeitrag: Date;
  public ivVerfuegteAssistenzberatung: number;
  public datumIvVerfuegung: Date;
  public erteilungVA: Date;
  public istFamiliennachzug: boolean;
  public fax: string;
  public hauptBehinderungsartCode: number;
  public hELBKeinAntrag: boolean;
  public hELBAb: Date;
  public hELBAnmeldung: Date;
  public hELBEntscheid: Date;
  public hELBEntscheidCode: number;
  public hilfslosenEntschaedigungCode: number;
  public imKantonSeit: Date;
  public imKantonSeitGeburt: boolean;
  public inGemeindeSeit: Date;
  public intensivPflegeZuschlagCode: number;
  public iVBerechtigungAnfangsStatusCode: number;
  public iVBerechtigungErsterEntscheidAb: Date;
  public iVBerechtigungErsterEntscheidCode: number;
  public iVBerechtigungZweiterEntscheidAb: Date;
  public iVBerechtigungZweiterEntscheidCode: number;
  public iVGrad: number;
  public iVHilfsmittel: boolean;
  public iVTaggeld: boolean;
  public keinSerienbrief: boolean;
  public konfessionCode: number;
  public kontoFuehrung: boolean;
  public baPersonID_Dossiertraeger: number;
  public kopfquote_BaInstitutionID: number;
  public kopfquoteAbDatum: Date;
  public kopfquoteBisDatum: Date;
  public korrespondenzSpracheCode: number;
  public kTG: boolean;
  public laufendeVollmachtErlaubnis: boolean;
  public manuelleAnrede: boolean;
  public medizinischeMassnahmeIV: boolean;
  public mehrfachbehinderung: boolean;
  public mietdepotPI: boolean;
  public migrationKA: number;
  public mobilTel: string;
  public navigatorZusatz: string;
  public passiveKopfQuote: boolean;
  public pauschaleAktualDatum: Date;
  public personSichtbarSDFlag: boolean;
  public projNr: number;
  public rentenstufeCode: number;
  public sichtbarSDFlag: boolean;
  public sozialhilfe: boolean;
  public sprachpauschale: number;
  public testperson: boolean;
  public untWohnsitzOrtCode: number;
  public uVGRente: boolean;
  public uVGTaggeld: boolean;
  public verstaendigungSprachCode: number;
  public visdat36Area: string;
  public visdat36ID: string;
  public vormundMassnahmenCode: number;
  public vormundPI: boolean;
  public wichtigerHinweis: string;
  public wittwenWittwerWaisenrente: boolean;
  public wohnstatusCode: number;
  public zeigeDetails: boolean;
  public zeigeTelGeschaeft: boolean;
  public zeigeTelMobil: boolean;
  public zeigeTelPrivat: boolean;
  public zEMISNummer: string;
  public istBerechnungsperson: boolean;
  public datumAsylgesuch: Date;
  public datumEinbezugFaz: Date;
  public verID: number;
  public creator: string;
  public created: Date;
  public modifier: string;
  public modified: Date;
  public verID_DELETED: number;
  public heimatort: string;
  public konfessionName: string;
  public auslaenderStatusName: string;
  public sprachName: string;
  public zivilstandName: string;
  public nationalitaetName: string;
  public untWohnsitzLandName: string;
  public zuzugKtLandName: string;
  public zuzugGdeLandName: string;
  public wegzugLandName: string;
  public geschlechtName: string;
  constructor(data?: IPersonalien) {
    if (data) {
      for (const property in data) {
        if (data.hasOwnProperty(property)) {
          (<any>this)[property] = (<any>data)[property];
        }
      }
    }
  }
}
